visible = false;
charName = "";
charText = "";
charSprite = DialogueSprite;
textIndex = 0;
textSpeed = 4; // скорость появления букв
textTimer = 0;
displayText = "";
currentNPC = noone;
nameSprite = -1;
choices = [];          // массив вариантов: [{text: "Да", nextIndex: 2}, {text: "Нет", nextIndex: 5}]
showingChoices = false;
selectedChoice = 0;
choiceBoxSprite = sChoiceBoxNormal;     // обычный спрайт окна реплики
choiceBoxSelectedSprite = sChoiceBoxSelected; // спрайт при выборе
choiceAreas = []; // координаты для мыши, заполняются динамически
currentDialogueList = [];
dialogueIndex       = 0;
_dialogue_sprite = DialogueWindow